### ISSUE TITLE
Dependency Issues

### ISSUE THREAD

**Issue by TheKrafter** [keyboardcat1/MineRTC#3]
Several classes appear to be missing when trying to enable the plugin.

Even after adding these lines to `src/main/resources/plugin.yml`:
```yaml
libraries:
  ...
  - org.eclipse.jetty:jetty-http:11.0.14
  - org.eclipse.jetty:jetty-util:11.0.14
  - org.eclipse.jetty:jetty-io:11.0.14
  - org.eclipse.jetty:jetty-servlet:11.0.14
  - org.eclipse.jetty:jetty-security:11.0.14
  - org.eclipse.jetty.websocket:websocket-common:9.4.53.v20231009
  - org.eclipse.jetty.websocket:websocket-core-common:11.0.14
  - org.eclipse.jetty.websocket:websocket-core-server:11.0.14
  - jakarta.servlet:jakarta.servlet-api:5.0.0
```
Yet another class is still missing:
<details>

```
[20:11:49 INFO]: [MineRTC] Enabling MineRTC v1.0.0*
[20:11:50 INFO]: [org.eclipse.jetty.server.Server] jetty-11.0.14; built: 2023-02-22T23:41:48.575Z; git: 4601fe8dd805ce75b69c64466c115a162586641b; jvm 17.0.9+9
[20:11:50 ERROR]: Error occurred while enabling MineRTC v1.0.0 (Is it up to date?)
java.lang.NoClassDefFoundError: org/eclipse/jetty/websocket/common/JettyWebSocketFrameHandlerFactory
	at java.lang.ClassLoader.defineClass1(Native Method) ~[?:?]
	at java.lang.ClassLoader.defineClass(ClassLoader.java:1017) ~[?:?]
	at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:150) ~[?:?]
	at java.net.URLClassLoader.defineClass(URLClassLoader.java:524) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:427) ~[?:?]
	at java.net.URLClassLoader$1.run(URLClassLoader.java:421) ~[?:?]
	at java.security.AccessController.doPrivileged(AccessController.java:712) ~[?:?]
	at java.net.URLClassLoader.findClass(URLClassLoader.java:420) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	at org.eclipse.jetty.websocket.server.JettyWebSocketServerContainer.<init>(JettyWebSocketServerContainer.java:134) ~[?:?]
	at org.eclipse.jetty.websocket.server.JettyWebSocketServerContainer.ensureContainer(JettyWebSocketServerContainer.java:83) ~[?:?]
	at org.eclipse.jetty.websocket.server.config.JettyWebSocketServletContainerInitializer.initialize(JettyWebSocketServletContainerInitializer.java:89) ~[?:?]
	at org.eclipse.jetty.websocket.server.config.JettyWebSocketServletContainerInitializer.onStartup(JettyWebSocketServletContainerInitializer.java:100) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContainerInitializerHolder.doStart(ServletContainerInitializerHolder.java:148) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[?:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler$ServletContainerInitializerStarter.doStart(ServletContextHandler.java:1660) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler.startContext(ServletContextHandler.java:369) ~[?:?]
	at org.eclipse.jetty.server.handler.ContextHandler.doStart(ContextHandler.java:903) ~[?:?]
	at org.eclipse.jetty.servlet.ServletContextHandler.doStart(ServletContextHandler.java:306) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.start(ContainerLifeCycle.java:171) ~[?:?]
	at org.eclipse.jetty.server.Server.start(Server.java:470) ~[?:?]
	at org.eclipse.jetty.util.component.ContainerLifeCycle.doStart(ContainerLifeCycle.java:114) ~[?:?]
	at org.eclipse.jetty.server.handler.AbstractHandler.doStart(AbstractHandler.java:89) ~[?:?]
	at org.eclipse.jetty.server.Server.doStart(Server.java:415) ~[?:?]
	at org.eclipse.jetty.util.component.AbstractLifeCycle.start(AbstractLifeCycle.java:93) ~[?:?]
	at io.github.keyboardcat1.minertc.web.AppServer.main(AppServer.java:67) ~[MineRTC-1.0-SNAPSHOT.jar:?]
	at io.github.keyboardcat1.minertc.MineRTC.onEnable(MineRTC.java:42) ~[MineRTC-1.0-SNAPSHOT.jar:?]
	at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:281) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at io.papermc.paper.plugin.manager.PaperPluginInstanceManager.enablePlugin(PaperPluginInstanceManager.java:190) ~[paper-1.20.4.jar:git-Paper-370]
	at io.papermc.paper.plugin.manager.PaperPluginManagerImpl.enablePlugin(PaperPluginManagerImpl.java:104) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:507) ~[paper-api-1.20.4-R0.1-SNAPSHOT.jar:?]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugin(CraftServer.java:637) ~[paper-1.20.4.jar:git-Paper-370]
	at org.bukkit.craftbukkit.v1_20_R3.CraftServer.enablePlugins(CraftServer.java:548) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.loadWorld0(MinecraftServer.java:673) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.loadLevel(MinecraftServer.java:433) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.dedicated.DedicatedServer.initServer(DedicatedServer.java:308) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:1132) ~[paper-1.20.4.jar:git-Paper-370]
	at net.minecraft.server.MinecraftServer.lambda$spin$0(MinecraftServer.java:321) ~[paper-1.20.4.jar:git-Paper-370]
	at java.lang.Thread.run(Thread.java:840) ~[?:?]
Caused by: java.lang.ClassNotFoundException: org.eclipse.jetty.websocket.common.JettyWebSocketFrameHandlerFactory
	at java.net.URLClassLoader.findClass(URLClassLoader.java:445) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:592) ~[?:?]
	at java.lang.ClassLoader.loadClass(ClassLoader.java:525) ~[?:?]
	... 44 more
[20:11:50 INFO]: [MineRTC] Disabling MineRTC v1.0.0
```

</details>

I'd love to use this plugin, but it just seems to not be in a useable state at the moment.

**Comment by keyboardcat1** [comment]
Hello again,
Indeed the plugin is still in development
This issue is due to using the wrong paper version, and should work on previous 1.19 versions
